### ISSUE TITLE
Como rodar sem Docker

### ISSUE THREAD

**Issue by DFBR1208** [felipemarinho97/torrent-indexer#11]
Opa amigo, estou querendo adicionar o indexer no meu Jackett, entretanto não tenho Docker e não pretendo por questão própria mesmo, mais costume com o Windows padrão. tentei adiocnar o .json no README no local do Jackett e o mesmo apenas excluiu como outro usuário citou. Sabe como posso fazer? Abraços!

**Comment by felipemarinho97** [comment]
Opa amigo, infelizmente estou sem tempo para escrever qualquer guia de uso sem Docker (já adianto que vai dar mais trabalho). Além disso, eu não consigo documentar o suporte a ambientes Windows (dado que não uso, e nem tenho a licença), então provavelmente qualquer guia feito por mim seria focado em sistemas GNU/Linux.

O projeto é open-source então quem tiver interesse pode escrever algum guia pro windows no futuro.

Por hora sugiro que tente rodar no docker mesmo, depois de instalado são só alguns poucos cliques usando o `docker-compose` para fazer funcionar.

**Comment by DFBR1208** [comment]
Acabei migrando para o seguinte guia usando o Prowlarr msm https://www.reddit.com/r/pirataria/comments/1d3i69f/guia_filmes_dublados_autom%C3%A1ticos_no_radarr_e/ de qualquer forma, obrigado!!
