### ISSUE TITLE
detecção de audio aprimorada sonarr e radarr

### ISSUE THREAD

**Issue by Thanegche** [felipemarinho97/torrent-indexer#15]
tentei alguns vezes alterar o arq audio.go para um formato mais apropriado para detecção do sonarr e radar para títulos em pt-br
apenas trocando o por por Brazilian e subir o container, mas a alteração não surge efeito kkk aqui em baixou esta oque eu detectei
estado atual https://ibb.co/jVN7skD https://ibb.co/c1sytFV
apenas títulos com dublado no título são detectados como portugues brasileiro
solução https://ibb.co/bddSs0h

**Comment by felipemarinho97** [comment]
Show demais hein @Thanegche !
Eu nunca tinha entendido direito porquê o radarr/sonarr não reconhecer direito a tag "por". Vou testar aqui e subir a alteração.
