### ISSUE TITLE
como usar poderia fazer um tutorial

### ISSUE THREAD

**Issue by Thanegche** [felipemarinho97/torrent-indexer#2]
Microsoft Windows [versão 10.0.22631.3155]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\thane\Downloads\torrent-indexer-main (1)\torrent-indexer-main>docker compose up
validating C:\Users\thane\Downloads\torrent-indexer-main (1)\torrent-indexer-main\docker-compose.yml: services.torrent-indexer.image must be a string

C:\Users\thane\Downloads\torrent-indexer-main (1)\torrent-indexer-main>

estou recebendo esse seguinte erro

**Comment by felipemarinho97** [comment]
Opa @Thanegche !
Você tem algum motivo para querer subir o serviço localmente?

É possivel usar no [https://vlambdas.oci.darklyn.online/](https://vlambdas.oci.darklyn.online/)

**Comment by Thanegche** [comment]
a minha real intenção era integrar ao jackett ou ao prowlarr para ter mais opções de indexadores para usa no sonarr e radarr observando as pastas imaginei q fosse necessário subir um container no docker mas aí subir o container da sua aplicação so que não faço a minima ideia de como fazer a integrção da mesma no jackett poderia-me dá uma ajuda sobre isso

**Comment by felipemarinho97** [comment]
Vou adicionar um seção no README sobre isso

**Comment by Thanegche** [comment]
> Vou adicionar um seção no README sobre isso

muito obg amigo
